# Generated by Django 6.0.7 on 2026-07-18 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_birthdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='registration_source',
            field=models.CharField(default='local', max_length=20, verbose_name='Источник регистрации'),
        ),
    ]
